import React, { useState, useEffect } from 'react';
import { Shield, ArrowRight, Loader2, Wallet } from 'lucide-react';
import { useDispatch, useSelector } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { verify2FALogin, clear2FA } from '../slices/authSlice';
import toast from 'react-hot-toast';

const TwoFAVerify = () => {
  const [token, setToken] = useState('');
  const { loading, requires2FA, tempEmail, error } = useSelector((state) => state.auth);
  const dispatch = useDispatch();
  const navigate = useNavigate();

  useEffect(() => {
    // If user lands here without requiring 2FA, redirect to login
    if (!requires2FA || !tempEmail) {
      navigate('/login');
    }
  }, [requires2FA, tempEmail, navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (token.length !== 6) return;

    const resultAction = await dispatch(verify2FALogin({ email: tempEmail, token }));
    if (verify2FALogin.fulfilled.match(resultAction)) {
      toast.success('Login successful!');
      navigate('/');
    } else {
      toast.error(resultAction.payload?.error || 'Invalid authentication code');
    }
  };

  const handleCancel = () => {
    dispatch(clear2FA());
    navigate('/login');
  };

  if (!requires2FA) return null;

  return (
    <div className="min-h-screen flex items-center justify-center p-6 bg-[radial-gradient(circle_at_top_right,_var(--tw-gradient-stops))] from-emerald-900/20 via-dark-bg to-dark-bg">
      <div className="w-full max-w-md">
        <div className="text-center mb-10">
          <div className="w-16 h-16 bg-emerald-500 rounded-3xl flex items-center justify-center shadow-2xl shadow-emerald-500/40 mx-auto mb-6 rotate-12">
            <Shield className="text-white" size={32} />
          </div>
          <h1 className="text-4xl font-bold text-white mb-2">Two-Step Verification</h1>
          <p className="text-slate-400">Enter the verification code generated by your authenticator app.</p>
        </div>

        <div className="glass-dark p-8 rounded-[2.5rem] border border-slate-700/50 shadow-2xl">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-300 ml-1">Authentication Code</label>
              <div className="relative">
                <Shield className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18} />
                <input 
                  type="text" 
                  value={token}
                  onChange={(e) => setToken(e.target.value.replace(/\D/g, '').slice(0, 6))}
                  placeholder="000000"
                  className="w-full bg-slate-800/50 border border-slate-700 rounded-2xl py-4 pl-12 pr-4 focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500 transition-all text-white font-mono tracking-[0.5em] text-center text-xl"
                  required
                  pattern="\d{6}"
                  maxLength={6}
                  autoFocus
                />
              </div>
            </div>

            <div className="flex gap-4">
              <button 
                type="button" 
                onClick={handleCancel}
                disabled={loading}
                className="flex-1 py-4 text-slate-400 font-semibold hover:text-white transition-colors"
              >
                Cancel
              </button>
              <button 
                type="submit" 
                disabled={loading || token.length !== 6}
                className="flex-[2] btn-primary flex items-center justify-center gap-2 py-4 disabled:opacity-50"
              >
                {loading ? <Loader2 className="animate-spin" size={18} /> : 'Verify & Login'}
                {!loading && <ArrowRight size={18} />}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default TwoFAVerify;
